### ISSUE TITLE
How do you actually use this?

### ISSUE THREAD

**Issue by Immortql** [canteventry/Trinity-crack#1]
I'd like to think that I'm not being an idiot, but this honestly has me kind of stumped (so I probably _am_ being an idiot).

I tried to set up a local server just to test the waters and see if this worked with PHP (php -S.. blah, blah, blah, you get it), and as the files are in the `server` directory, that's where I tried to execute it from (I tried other directories as well, but basically the same issues).

This however leads to multiple other problems such as there apparently being no `/` directory, and if you try to directly access any of the files via the URL, it throws errors such as the `MyDB` and `SQLite3` Classes not existing, or having errors.

I'm 100% sure that I'm doing this all wrong, but there's also no real information to get anyone started on trying to do anything with this besides the information about setting your Local IP Address to `192.168.0.4`.

I apologize if this is simple to set up, but I genuinely have zero experience with PHP. The only server-side things I've ever done was simple NodeJS projects, but that's not really comparable.

Anyways, if you're able to help at all I'd be immensely grateful.

**Comment by canteventry** [comment]
you just need to install sqlite extension for php, you have a couple of documentation for this, let me know if it helps

**Comment by Immortql** [comment]
Other than that though, is there anything else I'd need to know? Is it only the server I need to have up and the ELF does the rest, or do I need to create a launcher to use it with? Also is there anything I need to see PC side to confirm I did it correctly? Sorry if these questions are annoying, but I'm relatively new to this.

If I could get a full explanation on what I'm supposed to do I'd be extremely grateful.

**Comment by canteventry** [comment]
no, the elf file does everything

**Comment by canteventry** [comment]
do you have discord ?

**Comment by Immortql** [comment]
Unfortunately, no. I don't have any social media as I prefer to stay off of it.

But if I got the gist of it right, does that mean I CD into the `server` directory after changing my computer's IPv4 address to `192.168.0.4`, launch the PHP server with the `PHP -S ...` command, and then run the patched ELF in this repository on the console? If so, then I was just severely over complicating it in my head.

Also after reviewing some of the files I assume that the IP address that's used to point to the server is encoded in the ELF itself? Perhaps via an assembly element? If so, then I wouldn't be adverse to hosting a public server for launching this content after patching the ELF again. (If I can get it up securely, anyways).

If I've gotten anything wrong, please correct me. Like I said, I'm still  pretty new to stuff like this; so I'm bound to make mistakes. I think a repository like this could benefit from something like a setup guide to ensure ease of use, especially considering not all of this is common knowledge to everyone.

**Comment by canteventry** [comment]
it's correct. and yeah, the ip address is in the elf file as a string, how else could trinity connect? im goin to make a documentation to explain to the **skiddos** how to do it, so don't worry. for the public server, do whatever you want but i'll not connect to it personally due to security reason (ip grabbing 🤡), this is also one of the reasons why I preferred to give the src rather than make a public server.

**Comment by Immortql** [comment]
Thank you for clarifying. It seems I was just overthinking it.

**Comment by cedkechat01** [comment]
How to use Trinity Crack @Immortql ?
